'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contacto_Direcciones
    Public Property codigoDireccion As Integer
    Public Property direccion As String
    Public Property descripcion As String
    Public Property codigoContacto As Integer

    Public Overridable Property Contactos As Contactos

End Class
