'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contactos
    Public Property codigoContacto As Integer
    Public Property apellidos As String
    Public Property nombres As String
    Public Property codigoUsuario As Integer

    Public Overridable Property Contacto_Direcciones As ICollection(Of Contacto_Direcciones) = New HashSet(Of Contacto_Direcciones)
    Public Overridable Property Contacto_Email As ICollection(Of Contacto_Email) = New HashSet(Of Contacto_Email)
    Public Overridable Property Contacto_Telefonos As ICollection(Of Contacto_Telefonos) = New HashSet(Of Contacto_Telefonos)
    Public Overridable Property Usuarios As Usuarios

End Class
