// <auto-generated />
namespace SistemaInventario2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregarCampoPrecioCompraalaentidadRegistroCompras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregarCampoPrecioCompraalaentidadRegistroCompras));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251509152_Agregar Campo PrecioCompra a la entidad RegistroCompras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
